version: 2
updates:
  - package-ecosystem: gitsubmodule
    directory: /
    target-branch: master
    schedule:
      interval: cron
      cronjob: "0 * * * *"
    open-pull-requests-limit: 1
    labels:
      - dependencies
      - submodules

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly

  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly

  - package-ecosystem: bundler
    directory: /
    schedule:
      interval: weekly
