title: Leonardo Wajda
author: Leonardo Wajda
email: dev.leowajda@tuta.io
url: https://leowajda.github.io
baseurl: ""
description: ""

markdown: kramdown
highlighter: rouge

sass:
  sass_dir: _sass
  style: compressed

collections:
  problems:
    output: true
    permalink: /:path/
  problem_embeds:
    output: true
    permalink: /:path/
  source_modules:
    output: true
    permalink: /:path/
  source_documents:
    output: true
    permalink: /:path/

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

theme_config:
  appearance: "auto"
  date_format: "%Y-%m-%d"
  show_description: false
  lowercase_titles: false

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
  - scope:
      path: "eureka"
      type: pages
    values:
      layout: problems
      project_key: eureka
      custom_js:
        - eureka-filters
  - scope:
      path: ""
      type: problems
    values:
      layout: problem
  - scope:
      path: ""
      type: problem_embeds
    values:
      layout: problem_embed
  - scope:
      path: ""
      type: source_modules
    values:
      layout: source_module
  - scope:
      path: ""
      type: source_documents
    values:
      layout: source_document

generated_data_namespace: generated
