# frozen_string_literal: true

require_relative 'site_kit/core/constants'
require_relative 'site_kit/core/errors'
require_relative 'site_kit/core/io_helpers'
require_relative 'site_kit/core/validation_helpers'
require_relative 'site_kit/core/schema'
require_relative 'site_kit/core/path_helpers'
require_relative 'site_kit/core/resource_paths'
require_relative 'site_kit/core/markdown_helpers'
require_relative 'site_kit/core/collection_helpers'
require_relative 'site_kit/core/record_helpers'
require_relative 'site_kit/core/helpers'

require_relative 'site_kit/assets/version_manifest'

require_relative 'site_kit/catalogs/app_config_repository'
require_relative 'site_kit/catalogs/project_manifest_repository'
require_relative 'site_kit/catalogs/project_registry'
require_relative 'site_kit/catalogs/site_project_presenter'

require_relative 'site_kit/emit'

require_relative 'site_kit/templates/topic_repository'
require_relative 'site_kit/templates/problem_rules'
require_relative 'site_kit/templates/reference_label'
require_relative 'site_kit/templates/code_sources/repository'
require_relative 'site_kit/templates/code_collections/registry'
require_relative 'site_kit/templates/guide/index_builder'
require_relative 'site_kit/templates/guide/validator'
require_relative 'site_kit/templates/guide/reference_resolver'
require_relative 'site_kit/templates/guide/repository'
require_relative 'site_kit/templates/library_context'

require_relative 'site_kit/eureka/topics'
require_relative 'site_kit/eureka/source_catalog_loader'
require_relative 'site_kit/eureka/problem_registry_builder'
require_relative 'site_kit/eureka/page_factory'
require_relative 'site_kit/eureka/project'
require_relative 'site_kit/eureka/context'

require_relative 'site_kit/source_notes/tree_builder'
require_relative 'site_kit/source_notes/catalog_loader'
require_relative 'site_kit/source_notes/document_builder'
require_relative 'site_kit/source_notes/module_builder'
require_relative 'site_kit/source_notes/registry_builder'
require_relative 'site_kit/source_notes/page_factory'
require_relative 'site_kit/source_notes/project'
require_relative 'site_kit/source_notes/context'

require_relative 'site_kit/search/record'
require_relative 'site_kit/extras/pagefind'

require_relative 'site_kit/jekyll_runtime/site_loader'
require_relative 'site_kit/jekyll_runtime/generated_page'
require_relative 'site_kit/checks/internal_links'
require_relative 'site_kit/checks/seo_metadata'
require_relative 'site_kit/checks/site_invariants'
require_relative 'site_kit/checks/source_catalogs'
require_relative 'site_kit/checks/vendor_assets'

require_relative 'site_kit/runtime'
